import { useState } from "react";
import "./AppHeader.css";
import App from "./App";


function AppHeader() {
  
  const [menus,setMenuss] = useState([{"name":"Create Rules",location:0,description:"Create custom rules",count:0}
    ,{"name":"Alerts",location:1,description:"Alerts generated by your rule",count:1}
    ,{"name":"P&L",location:2,description:"Profit and loss create by system",count:0}
    ,{"name":"Monitor List",location:3,description:"Assets monitored by system",count:0},
    ,{"name":"Rules",location:4,description:"Rules under the system",count:0}
  ]);
  const [menu, setMenu] = useState(menus[1]);//default to first menu
  const [menuCountSelected, setMCountSelected] =useState(2);

  function handleClick(event,location){
    if(location !=null && location != undefined)
    {
      var selectedMenu = menus[location];// = 0;//reset alert
      selectedMenu.count =0;
      console.log("das"+ menus[location].count);
      setMenuss(menus);
      setMenu(selectedMenu);
      setMCountSelected(location);
    }
    else{
      console.log("location came null");
    }
  }
  function updateMenu(location,numberOfAlert){
    if(numberOfAlert!==undefined && location!== undefined && numberOfAlert>0 ){
      menus[location]["count"] = numberOfAlert;
      //how to refresh only menu
    }
  }
  console.log(menus[1].count);
  return (
    
  <div>
    <div className="header">
      <a href="#default" className="logo">{menu.description}</a>
      <div className="header-right">
        {menus.map((eachMenu, i) => (i===menuCountSelected)?(
              <a  className="active" href="#{eachMenu.location}">{eachMenu.name}{eachMenu.count>0?(<i>{eachMenu.count}</i>):(<br/>)}</a>
              ):(
              <a onClick={(event) => handleClick(event, i)} href="#{eachMenu.location}">{eachMenu.name}{eachMenu.count>0?(<i>({eachMenu.count})</i>):(<br/>)}</a>
              ) )}
      </div>
    </div>
    <div>
        <App  tabName={menu.name} menuOperation={updateMenu}/>
    </div>
  </div>
  );
}

export default AppHeader;